//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eve_Control.RelayServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceRequestDetails", Namespace="http://schemas.datacontract.org/2004/07/Eve.API.Services.Contracts.Services")]
    [System.SerializableAttribute()]
    public partial class ServiceRequestDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Eve_Control.RelayServiceReference.ServiceClient ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Eve_Control.RelayServiceReference.ServiceUser UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Eve_Control.RelayServiceReference.ServiceClient Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Eve_Control.RelayServiceReference.ServiceUser User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceClient", Namespace="http://schemas.datacontract.org/2004/07/Eve.API.Services.Contracts.Services")]
    [System.SerializableAttribute()]
    public partial class ServiceClient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alias {
            get {
                return this.AliasField;
            }
            set {
                if ((object.ReferenceEquals(this.AliasField, value) != true)) {
                    this.AliasField = value;
                    this.RaisePropertyChanged("Alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceUser", Namespace="http://schemas.datacontract.org/2004/07/Eve.API.Services.Contracts.Services")]
    [System.SerializableAttribute()]
    public partial class ServiceUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsValid {
            get {
                return this.IsValidField;
            }
            set {
                if ((this.IsValidField.Equals(value) != true)) {
                    this.IsValidField = value;
                    this.RaisePropertyChanged("IsValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordHash {
            get {
                return this.PasswordHashField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordHashField, value) != true)) {
                    this.PasswordHashField = value;
                    this.RaisePropertyChanged("PasswordHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrackPadMessage", Namespace="http://schemas.datacontract.org/2004/07/Eve.API.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class TrackPadMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AngleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Eve_Control.RelayServiceReference.TrackPadMessage.TrackPadCommands CommandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Eve_Control.RelayServiceReference.Orientation DirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DistanceRatioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double YField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Angle {
            get {
                return this.AngleField;
            }
            set {
                if ((this.AngleField.Equals(value) != true)) {
                    this.AngleField = value;
                    this.RaisePropertyChanged("Angle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Eve_Control.RelayServiceReference.TrackPadMessage.TrackPadCommands Command {
            get {
                return this.CommandField;
            }
            set {
                if ((this.CommandField.Equals(value) != true)) {
                    this.CommandField = value;
                    this.RaisePropertyChanged("Command");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Eve_Control.RelayServiceReference.Orientation Direction {
            get {
                return this.DirectionField;
            }
            set {
                if ((this.DirectionField.Equals(value) != true)) {
                    this.DirectionField = value;
                    this.RaisePropertyChanged("Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DistanceRatio {
            get {
                return this.DistanceRatioField;
            }
            set {
                if ((this.DistanceRatioField.Equals(value) != true)) {
                    this.DistanceRatioField = value;
                    this.RaisePropertyChanged("DistanceRatio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="TrackPadMessage.TrackPadCommands", Namespace="http://schemas.datacontract.org/2004/07/Eve.API.Services.Contracts")]
        public enum TrackPadCommands : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Tap = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Hold = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            DoubleTap = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Flick = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            DragStarted = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            DragDelta = 5,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            DragCompleted = 6,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PinchStarted = 7,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PinchDelta = 8,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PinchCompleted = 9,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="Orientation", Namespace="http://schemas.datacontract.org/2004/07/Eve.API.Services.Contracts")]
    public enum Orientation : uint {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Horizontal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Vertical = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ButtonMessage", Namespace="http://schemas.datacontract.org/2004/07/Eve.API.Services.Contracts")]
    [System.SerializableAttribute()]
    public partial class ButtonMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Eve_Control.RelayServiceReference.ButtonMessage.Buttons ButtonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Eve_Control.RelayServiceReference.ButtonMessage.ButtonCommands CommandField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Eve_Control.RelayServiceReference.ButtonMessage.Buttons Button {
            get {
                return this.ButtonField;
            }
            set {
                if ((this.ButtonField.Equals(value) != true)) {
                    this.ButtonField = value;
                    this.RaisePropertyChanged("Button");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Eve_Control.RelayServiceReference.ButtonMessage.ButtonCommands Command {
            get {
                return this.CommandField;
            }
            set {
                if ((this.CommandField.Equals(value) != true)) {
                    this.CommandField = value;
                    this.RaisePropertyChanged("Command");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.FlagsAttribute()]
        [System.Runtime.Serialization.DataContractAttribute(Name="ButtonMessage.Buttons", Namespace="http://schemas.datacontract.org/2004/07/Eve.API.Services.Contracts")]
        public enum Buttons : uint {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Left = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Right = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Middle = 3,
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.FlagsAttribute()]
        [System.Runtime.Serialization.DataContractAttribute(Name="ButtonMessage.ButtonCommands", Namespace="http://schemas.datacontract.org/2004/07/Eve.API.Services.Contracts")]
        public enum ButtonCommands : uint {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Tap = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Hold = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            DoubleTap = 4,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientState", Namespace="http://schemas.datacontract.org/2004/07/Eve.API.Services.Contracts.Services")]
    [System.SerializableAttribute()]
    public partial class ClientState : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RelayServiceReference.IRelayService", CallbackContract=typeof(Eve_Control.RelayServiceReference.IRelayServiceCallback))]
    public interface IRelayService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITouchService/SendTrackPadMessage", ReplyAction="http://tempuri.org/ITouchService/SendTrackPadMessageResponse")]
        bool SendTrackPadMessage(Eve_Control.RelayServiceReference.ServiceRequestDetails details, Eve_Control.RelayServiceReference.TrackPadMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITouchService/SendTrackPadMessage", ReplyAction="http://tempuri.org/ITouchService/SendTrackPadMessageResponse")]
        System.Threading.Tasks.Task<bool> SendTrackPadMessageAsync(Eve_Control.RelayServiceReference.ServiceRequestDetails details, Eve_Control.RelayServiceReference.TrackPadMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITouchService/SendButtonMessage", ReplyAction="http://tempuri.org/ITouchService/SendButtonMessageResponse")]
        bool SendButtonMessage(Eve_Control.RelayServiceReference.ServiceRequestDetails details, Eve_Control.RelayServiceReference.ButtonMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITouchService/SendButtonMessage", ReplyAction="http://tempuri.org/ITouchService/SendButtonMessageResponse")]
        System.Threading.Tasks.Task<bool> SendButtonMessageAsync(Eve_Control.RelayServiceReference.ServiceRequestDetails details, Eve_Control.RelayServiceReference.ButtonMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEveAPIService/Ping", ReplyAction="http://tempuri.org/IEveAPIService/PingResponse")]
        string Ping(string yourName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEveAPIService/Ping", ReplyAction="http://tempuri.org/IEveAPIService/PingResponse")]
        System.Threading.Tasks.Task<string> PingAsync(string yourName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEveAPIService/SignIn", ReplyAction="http://tempuri.org/IEveAPIService/SignInResponse")]
        bool SignIn(Eve_Control.RelayServiceReference.ServiceUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEveAPIService/SignIn", ReplyAction="http://tempuri.org/IEveAPIService/SignInResponse")]
        System.Threading.Tasks.Task<bool> SignInAsync(Eve_Control.RelayServiceReference.ServiceUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEveAPIService/SignOut", ReplyAction="http://tempuri.org/IEveAPIService/SignOutResponse")]
        bool SignOut(Eve_Control.RelayServiceReference.ServiceUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEveAPIService/SignOut", ReplyAction="http://tempuri.org/IEveAPIService/SignOutResponse")]
        System.Threading.Tasks.Task<bool> SignOutAsync(Eve_Control.RelayServiceReference.ServiceUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEveAPIService/GetClientState", ReplyAction="http://tempuri.org/IEveAPIService/GetClientStateResponse")]
        Eve_Control.RelayServiceReference.ClientState GetClientState();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEveAPIService/GetClientState", ReplyAction="http://tempuri.org/IEveAPIService/GetClientStateResponse")]
        System.Threading.Tasks.Task<Eve_Control.RelayServiceReference.ClientState> GetClientStateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEveAPIService/GetAvailableClients", ReplyAction="http://tempuri.org/IEveAPIService/GetAvailableClientsResponse")]
        Eve_Control.RelayServiceReference.ServiceClient[] GetAvailableClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEveAPIService/GetAvailableClients", ReplyAction="http://tempuri.org/IEveAPIService/GetAvailableClientsResponse")]
        System.Threading.Tasks.Task<Eve_Control.RelayServiceReference.ServiceClient[]> GetAvailableClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRelayService/Subscribe")]
        void Subscribe();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRelayService/Subscribe")]
        System.Threading.Tasks.Task SubscribeAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRelayService/Unsibscribe")]
        void Unsibscribe();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRelayService/Unsibscribe")]
        System.Threading.Tasks.Task UnsibscribeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRelayService/UpdateClientState", ReplyAction="http://tempuri.org/IRelayService/UpdateClientStateResponse")]
        bool UpdateClientState(Eve_Control.RelayServiceReference.ClientState state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRelayService/UpdateClientState", ReplyAction="http://tempuri.org/IRelayService/UpdateClientStateResponse")]
        System.Threading.Tasks.Task<bool> UpdateClientStateAsync(Eve_Control.RelayServiceReference.ClientState state);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRelayServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRelayService/PingRequest", ReplyAction="http://tempuri.org/IRelayService/PingRequestResponse")]
        string PingRequest(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRelayServiceChannel : Eve_Control.RelayServiceReference.IRelayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RelayServiceClient : System.ServiceModel.DuplexClientBase<Eve_Control.RelayServiceReference.IRelayService>, Eve_Control.RelayServiceReference.IRelayService {
        
        public RelayServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public RelayServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public RelayServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public RelayServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public RelayServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool SendTrackPadMessage(Eve_Control.RelayServiceReference.ServiceRequestDetails details, Eve_Control.RelayServiceReference.TrackPadMessage message) {
            return base.Channel.SendTrackPadMessage(details, message);
        }
        
        public System.Threading.Tasks.Task<bool> SendTrackPadMessageAsync(Eve_Control.RelayServiceReference.ServiceRequestDetails details, Eve_Control.RelayServiceReference.TrackPadMessage message) {
            return base.Channel.SendTrackPadMessageAsync(details, message);
        }
        
        public bool SendButtonMessage(Eve_Control.RelayServiceReference.ServiceRequestDetails details, Eve_Control.RelayServiceReference.ButtonMessage message) {
            return base.Channel.SendButtonMessage(details, message);
        }
        
        public System.Threading.Tasks.Task<bool> SendButtonMessageAsync(Eve_Control.RelayServiceReference.ServiceRequestDetails details, Eve_Control.RelayServiceReference.ButtonMessage message) {
            return base.Channel.SendButtonMessageAsync(details, message);
        }
        
        public string Ping(string yourName) {
            return base.Channel.Ping(yourName);
        }
        
        public System.Threading.Tasks.Task<string> PingAsync(string yourName) {
            return base.Channel.PingAsync(yourName);
        }
        
        public bool SignIn(Eve_Control.RelayServiceReference.ServiceUser user) {
            return base.Channel.SignIn(user);
        }
        
        public System.Threading.Tasks.Task<bool> SignInAsync(Eve_Control.RelayServiceReference.ServiceUser user) {
            return base.Channel.SignInAsync(user);
        }
        
        public bool SignOut(Eve_Control.RelayServiceReference.ServiceUser user) {
            return base.Channel.SignOut(user);
        }
        
        public System.Threading.Tasks.Task<bool> SignOutAsync(Eve_Control.RelayServiceReference.ServiceUser user) {
            return base.Channel.SignOutAsync(user);
        }
        
        public Eve_Control.RelayServiceReference.ClientState GetClientState() {
            return base.Channel.GetClientState();
        }
        
        public System.Threading.Tasks.Task<Eve_Control.RelayServiceReference.ClientState> GetClientStateAsync() {
            return base.Channel.GetClientStateAsync();
        }
        
        public Eve_Control.RelayServiceReference.ServiceClient[] GetAvailableClients() {
            return base.Channel.GetAvailableClients();
        }
        
        public System.Threading.Tasks.Task<Eve_Control.RelayServiceReference.ServiceClient[]> GetAvailableClientsAsync() {
            return base.Channel.GetAvailableClientsAsync();
        }
        
        public void Subscribe() {
            base.Channel.Subscribe();
        }
        
        public System.Threading.Tasks.Task SubscribeAsync() {
            return base.Channel.SubscribeAsync();
        }
        
        public void Unsibscribe() {
            base.Channel.Unsibscribe();
        }
        
        public System.Threading.Tasks.Task UnsibscribeAsync() {
            return base.Channel.UnsibscribeAsync();
        }
        
        public bool UpdateClientState(Eve_Control.RelayServiceReference.ClientState state) {
            return base.Channel.UpdateClientState(state);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateClientStateAsync(Eve_Control.RelayServiceReference.ClientState state) {
            return base.Channel.UpdateClientStateAsync(state);
        }
    }
}
